"""primeira_versao

Revision ID: 468b5d5c02b3
Revises: 
Create Date: 2026-01-05 00:47:56.262665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468b5d5c02b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulario',
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta',
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao',
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('quantidade_respostas', sa.Integer(), nullable=True),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questao')
    op.drop_table('pergunta')
    op.drop_table('formulario')
    # ### end Alembic commands ###
